import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import accountsRouter from "./accounts";
import projectsRouter from "./projects";
import milestonesRouter from "./milestones";
import tasksRouter from "./tasks";
import resourcesRouter from "./resources";
import allocationsRouter from "./allocations";
import timesheetsRouter from "./timesheets";
import invoicesRouter from "./invoices";
import opportunitiesRouter from "./opportunities";
import proposalsRouter from "./proposals";
import changeRequestsRouter from "./change_requests";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import templatesRouter from "./templates";
import staffingRequestsRouter from "./staffing_requests";
import contractsRouter from "./contracts";
import rateCardsRouter from "./rate_cards";
import taskResourcesRouter from "./task_resources";
import financeRouter from "./finance";
import formsRouter from "./forms";
import accountHealthRouter from "./account_health";
import automationsRouter from "./automations";
import closureRouter from "./closure";
import handoverRouter from "./handover";
import handoffRouter from "./handoff";
import searchRouter from "./search";
import adminRouter from "./admin";
import milestoneCommentsRouter from "./milestone_comments";
import digestRouter from "./digest";
import aiSummariesRouter from "./ai_summaries";
import timeEntryCategoriesRouter from "./time_entry_categories";
import templateTasksRouter from "./template_tasks";
import fxRatesRouter from "./fx_rates";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(accountsRouter);
router.use(projectsRouter);
router.use(milestonesRouter);
router.use(tasksRouter);
router.use(resourcesRouter);
router.use(allocationsRouter);
router.use(timesheetsRouter);
router.use(invoicesRouter);
router.use(opportunitiesRouter);
router.use(proposalsRouter);
router.use(changeRequestsRouter);
router.use(notificationsRouter);
router.use(dashboardRouter);
router.use(templatesRouter);
router.use(staffingRequestsRouter);
router.use(contractsRouter);
router.use(rateCardsRouter);
router.use(financeRouter);
router.use(formsRouter);

// Phase 5 — must register before generic :id routes
router.use(accountHealthRouter);
router.use(automationsRouter);
router.use(closureRouter);
router.use(handoverRouter);
router.use(handoffRouter);
router.use(searchRouter);
router.use(adminRouter);
router.use(milestoneCommentsRouter);
router.use(digestRouter);
router.use(aiSummariesRouter);
router.use(timeEntryCategoriesRouter);
router.use(taskResourcesRouter);
router.use(templateTasksRouter);
router.use(fxRatesRouter);

export default router;
